### ISSUE TITLE
Only one of the RTCP streams shows up on QoS tab

### ISSUE THREAD

**Issue by rogelio-telnyx** [sipcapture/homer-view#12]
The heplify server is receiving RTCP messages for both streams, and we can see both of them on the Messages tab, but only one of them is showing up on the QoS tab.
We suspect there might be something that homer-view doesn't like from the second stream which is preventing it from showing up.
Note: this issue happens also on the QoS tab of the homer app.
I'm sending attached screenshots from both tabs as well as the exported pcaps.
Can you please review and confirm why is it not showing up?

Thanks
![image(3)](https://user-images.githubusercontent.com/10601750/80778738-bf7c0d00-8b3f-11ea-81b3-a59253e17365.png)
![image(2)](https://user-images.githubusercontent.com/10601750/80778740-c276fd80-8b3f-11ea-87e3-67d64736a6cd.png)

[export_96616646.zip](https://github.com/sipcapture/homer-view/files/4562365/export_96616646.zip)

**Comment by adubovikov** [comment]
Hi @rogelio-telnyx , can you please provide us the dump of SIP and RTCP table with data of this call ? It will be easy to debug it! Thank you!

**Comment by gledim** [comment]
Hi @adubovikov 

Please find attached the data related to this call in **homer_data** DB.

Please let us know if there is anything else we can provide.

Thank you

[8klQgWLv3Hy4uHcA_d4v_w...zip](https://github.com/sipcapture/homer-view/files/4575979/8klQgWLv3Hy4uHcA_d4v_w.zip)

**Comment by adubovikov** [comment]
I think the issue has been fixed already. @jacovinus can you please confirm ?

**Comment by jacovinus** [comment]
Hello @gledim, It was fixed and committed to master branch. Let us know if you have further issues about RTCP streams.

**Comment by gledim** [comment]
Thank you, we have upgraded to the latest version, and we see QOS for both legs.

**Comment by gledim** [comment]
Hi @jacovinus @adubovikov, unfortunately the issue seems to be still there, but only in particular cases.

We have upgraded to the latest version of homer-app, and besides this issue, we notice another one, which happens in all the cases that we have seen so far. 

The RTCP messages do not appear in the "Messages" tab, even though they exist in the "hep_proto_5_default". Weird thing is that "QOS" tab has data about these messages (either with one stream or two). 
The _cdr_ request get "{"data":"","message":"no agent subscription object found for type [cdr]"}" as a response, while _qos_ request gets a complete JSON with data from the respective table.

Regarding the issue where "QOS" tab shows only one leg, even though as mentioned above QOS data for both legs exists in the respective table and is loaded upon request, we have dug a bit further, and see that there is a difference in the _raw_ field for the messages that get loaded, and the ones that do not. The ones that get loaded, have **type:200**, while the ones that do not, have **type:201**
Attached is a CSV with the RTCP data.
Please let us know if there is something else we can do to help
[RTCP_10072020.zip](https://github.com/sipcapture/homer-view/files/4904533/RTCP_10072020.zip)

**Comment by mikegoodstadt** [comment]
Hi @gledim - can you send us PCAP with the data?

**Comment by gledim** [comment]
Hi @mikegoodstadt 

Please find attached the pcap with SIP and RTCP for a call example.

[rtcp.zip](https://github.com/sipcapture/homer-view/files/4915223/rtcp.zip)

**Comment by AlexeyOplachko** [comment]
Hi @gledim can you please also provide information about what agent you use to send the traffic? Thanks

**Comment by gledim** [comment]
Hi @AlexeyOplachko!
The parties involved in this leg of the call are a Zoiper5 softphone and a FreeSwitch instance. The capture is performed by the integrated capture agent in Freeswitch

**Comment by AlexeyOplachko** [comment]
Hi @gledim 
We were trying to replicate your issue but it's just not happening on our test environment with PCAP you sent us.
Since capture was performed on integrated capture agent of Freeswitch we couldn't replicate that, so we sent it via Heplify
Homer app version used is 1.2.1
Homer view version used latest master branch build
Heplify version 1.61
![image](https://user-images.githubusercontent.com/45398541/88186846-70291280-cc3e-11ea-8276-482d5a0373de.png)
![image](https://user-images.githubusercontent.com/45398541/88186869-79b27a80-cc3e-11ea-8d06-ab83bd41df41.png)
And we're experiencing same behavior on Homer 7.8.1

**Comment by gledim** [comment]
Hi @AlexeyOplachko, thank you for checking on this.

It's really weird, as we are on the latest versions of homer-app, homer-view, and heplify.

Assuming that the missing RTCP messages issue might be a front-end issue, we have tried to replicate it in Chrome, Brave and Firefox, and it's happening in all three of them.

Please let us know if there is anything we can do to help in narrowing down the issue

**Comment by AlexeyOplachko** [comment]
Hi @gledim
I thought of one thing that may help, if you can please send copies of XHR request payload and response to "transaction" and to "qos" from Chrome Devtools Network tab

**Comment by gledim** [comment]
Hi @AlexeyOplachko 

Please find attached another example, including the XHR payloads for "transaction" and "qos", a pcap and the RTCP from hep_proto_5_default.

Please let us know if you need anything else

[call2.zip](https://github.com/sipcapture/homer-view/files/4967684/call2.zip)

**Comment by lmangani** [comment]
Reopening pending validation from @gledim and team

**Comment by gledim** [comment]
Hi team!

Thank you for the solution!

We merged the changes from your dev branch, and we couldn't spot the issues anymore.

RTCP messages show up, and the QOS tab displays 2 streams, so we can consider this fixed.

Please take in consideration that the same exact issue is also happening in homer-app, so maybe this fix might work there as well. If there is anything that we can help with about it, please let us know

CC: @mikegoodstadt @AlexeyOplachko @lmangani

**Comment by lmangani** [comment]
well done @AlexeyOplachko and team! The same issue should be already addressed in `homer-app` but we'll further confirm.
